name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: languages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # language plugin
          base: header
          config_order: base.header, isocalendar, languages
          plugin_isocalendar: yes
          
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_skipped: lowlighter/metrics, Freddd13/obsidian-main
          plugin_languages_threshold: 1%
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used

      # - name: Favorites anime and currently watching
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: metrics.plugin.anilist.svg
      #     token: NOT_NEEDED
      #     base: ""
      #     plugin_anilist: yes
      #     plugin_anilist_user: ${{ secrets.ANILIST_USER }}
      #     plugin_anilist_medias: anime
      #     plugin_anilist_sections: favorites
      #     plugin_anilist_limit: 2

